{
    "batch_size": 1000,
    "ignore_rows": {},
    "columns_details": [
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "Id",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "EncounterId",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "ENCOUNTER_ID",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "Notes",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "NOTES",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "ProviderAction",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": True,
            "mask_value": "",
            "column_name": "patient_id",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "PATIENT_ID_PATIENTID",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "mask_value": "",
            "column_name": "erx_req_id",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": "",
            "column_name_for_phi_table": None,
        },
        {
            "is_phi": False,
            "column_name": "nd_auto_increment_id",
            "ignore_rows": {},
            "add_to_phi_table": False,
            "reference_mapping": {},
            "de_identification_rule": None,
            "column_name_for_phi_table": None,
        },
    ],
    "reference_mapping": {},
    "reference_enc_id_column": "EncounterId",
    "reference_patient_id_column": None,
}
